services:
  app:
    build: 
      context:
    ports:
      - "6000:5000"
    volumes:
      - ./app/app
    command: python app.py

  mongodb:
    image: "mongo"
    ports: "27017-27019:27017-27019"