services:
  app:
    build: 
      context: app/
    ports:
      - "6000:5000"
    volumes:
      - ./app:/app
    command: python app.py

  mongodb:
    image: mongo:latest
    ports: 
      - "27017:27017"